export const LOAD_PROJECTS_SUCCESS = 'LOAD_PROJECTS_SUCCESS';

export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';

export const LOAD_MEMBERSHIPS_SUCCESS = 'LOAD_MEMBERSHIPS_SUCCESS';
export const LOAD_MEMBERSHIPS_FAILURE = 'LOAD_MEMBERSHIPS_FAILURE';

export const LOAD_TEAMS_SUCCESS = 'LOAD_TEAMS_SUCCESS';
export const LOAD_TEAMS_FAILURE = 'LOAD_TEAMS_FAILURE';

export const LOAD_TEAM_MEMBERS_SUCCESS = 'LOAD_TEAM_MEMBERS_SUCCESS';
export const LOAD_TEAM_MEMBERS_FAILURE = 'LOAD_TEAM_MEMBERS_FAILURE';

export const TOGGLE_PROJECT = 'TOGGLE_PROJECT';
export const TOGGLE_TEAM = 'TOGGLE_TEAM';

export const EMAIL_ON_CHANGE = 'EMAIL_ON_CHANGE'
export const API_TOKEN_ON_CHANGE = 'API_TOKEN_ON_CHANGE'
